### PR TITLE
Update PsykaniumInvHotkey_localization.lua

### PR DESCRIPTION
**Pull request by xsSplater**

### CODE REVIEW

**Comment by deluxghost** [comment]
Could you merge multiple PRs into one instead?

**Comment by xsSplater** [comment]
I'm sorry. I just updated all the mods on the list. Besides, I don't really know how to put it all together.

**Comment by deluxghost** [comment]
on your forked repo page, make sure your `main` branch is synced (there is a sync button). now you can press `.` key to open an online editor. checkout a new branch there (`patch-1` for example), modify all files you need, after that, commit all changes. you can open a PR from that branch

all-in-one PR is easier to check file diffs

**Comment by deluxghost** [comment]
did you join darktide modder discord server? you can get help there, and several modders might also want to discuss https://discord.gg/GFyCGNpJb8

**Pull request merged**
